Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from policyengine_core.country_template.constants import COUNTRY_DIR
from policyengine_core.data import Dataset
from policyengine_core.periods import ETERNITY, MONTH, period


class CountryTemplateDataset(Dataset):
    # Specify metadata used to describe and store the dataset.
    name = "country_template_dataset"
    label = "Country template dataset"
    folder_path = COUNTRY_DIR / "data" / "storage"
    data_format = Dataset.TIME_PERIOD_ARRAYS

    # The generation function is the most important part: it defines
    # how the dataset is generated from the raw data for a given year.
    def generate(self, year: int) -> None:
        person_id = [0, 1, 2]
        household_id = [0, 1]
        person_household_id = [0, 0, 1]
        person_household_role = ["parent", "child", "parent"]
        salary = [100, 0, 200]
        salary_time_period = period("2022-01")
        weight = [1e6, 1.2e6]
        weight_time_period = period("2022")
        data = {
            "person_id": {ETERNITY: person_id},
            "household_id": {ETERNITY: household_id},
            "person_household_id": {ETERNITY: person_household_id},
            "person_household_role": {ETERNITY: person_household_role},
            "salary": {salary_time_period: salary},
            "household_weight": {weight_time_period: weight},
        }
        self.save_variable_values(year, data)


# Important: we must instantiate datasets. This tests their validity and adds dynamic logic.
CountryTemplateDataset = CountryTemplateDataset()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[1], line 36[0m
[1;32m     32[0m         [38;5;28mself[39m[38;5;241m.[39msave_variable_values(year, data)
[1;32m     35[0m [38;5;66;03m# Important: we must instantiate datasets. This tests their validity and adds dynamic logic.[39;00m
[0;32m---> 36[0m CountryTemplateDataset [38;5;241m=[39m [43mCountryTemplateDataset[49m[43m([49m[43m)[49m

File [0;32m~/work/policyengine-core/policyengine-core/policyengine_core/data/dataset.py:39[0m, in [0;36mDataset.__init__[0;34m(self, regenerate)[0m
[1;32m     36[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, regenerate: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m):
[1;32m     37[0m     [38;5;66;03m# Setup dataset[39;00m
[1;32m     38[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mfile_path [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m---> 39[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m     40[0m             [38;5;124m"[39m[38;5;124mDataset file_path must be specified in the dataset class definition.[39m[38;5;124m"[39m
[1;32m     41[0m         )
[1;32m     42[0m     [38;5;28;01melif[39;00m [38;5;28misinstance[39m([38;5;28mself[39m[38;5;241m.[39mfile_path, [38;5;28mstr[39m):
[1;32m     43[0m         [38;5;28mself[39m[38;5;241m.[39mfile_path [38;5;241m=[39m Path([38;5;28mself[39m[38;5;241m.[39mfile_path)

[0;31mValueError[0m: Dataset file_path must be specified in the dataset class definition.

